name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP 25.2 / Elixir 1.14
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.2
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
